# Generated by Django 6.0.3 on 2026-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_encrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
